name: deploy preview
on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_ORG: gobazzinga-inc-584

jobs:
  build_binary:
    uses: ./.github/workflows/build-binary.yml
    with:
      publish-artifact: true

  destroy_preview:
    if: ${{github.event.pull_request.state == 'closed'}}
    runs-on: ubuntu-latest
    environment:
      name: pr-${{ github.event.number }}
      url: ${{ steps.deploy.outputs.url }}

    steps:
      - name: Deploy
        id: destroy
        uses: superfly/fly-pr-review-apps@1.2.1

  preview:
    if: ${{ github.event.pull_request.state == 'open'}}
    needs: build_binary
    runs-on: ubuntu-latest

    # Only run one deployment at a time per PR.
    concurrency:
      group: pr-${{ github.event.number }}

    # Create a GitHub deployment environment per staging app so it shows up
    # in the pull request UI.
    environment: Deployment

    steps:
      - uses: actions/checkout@v3
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: built-binary
      - run: |
          mkdir -p target/x86_64-unknown-linux-musl/release
          mv storj-interface target/x86_64-unknown-linux-musl/release/storj-interface
          chmod +x target/x86_64-unknown-linux-musl/release/storj-interface

      - name: Deploy
        id: deploy
        uses: superfly/fly-pr-review-apps@1.5.0
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_PR_PREVIEW_DEPLOYMENT_API_TOKEN }}
          FLY_ORG: gobazzinga-inc-584
        with:
          secrets: |
            STORJ_ACCESS_GRANT_SFW=${{ secrets.STORJ_ACCESS_GRANT }}
            STORJ_ACCESS_GRANT_NSFW=${{ secrets.STORJ_ACCESS_GRANT }}
            SFW_BUCKET=yral-videos
            NSFW_BUCKET=yral-nsfw-videos
            SERVICE_SECRET_TOKEN=${{ secrets.SERVICE_SECRET_TOKEN }}
            HETZNER_S3_ENDPOINT=${{ secrets.HETZNER_S3_ENDPOINT }}
            HETZNER_S3_ACCESS_KEY=${{ secrets.HETZNER_S3_ACCESS_KEY }}
            HETZNER_S3_SECRET_KEY=${{ secrets.HETZNER_S3_SECRET_KEY }}
            HETZNER_S3_BUCKET=${{ secrets.HETZNER_S3_BUCKET }}
            HETZNER_S3_REGION=${{ secrets.HETZNER_S3_REGION }}
      - name: Clean up GitHub environment
        uses: strumwolf/delete-deployment-environment@v2
        if: ${{ github.event.action == 'closed' }}
        with:
          # ⚠️ The provided token needs permission for admin write:org
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: pr-${{ github.event.number }}

  e2e-tests:
    needs: preview
    uses: ./.github/workflows/e2e-tests.yml
    if: ${{ github.event.pull_request.state == 'open'}}
    secrets: inherit
    with:
      preview_url: https://pr-${{github.event.number}}-dolr-ai-storj-interface.fly.dev
      publisher: testuser-${{ github.sha }}

