name: Publish latest image
on:
  push:
    branches:
      - main

jobs:
  build_binary:
    uses: ./.github/workflows/build-binary.yml
    with:
      publish-artifact: true

  publish:
    needs: build_binary
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: built-binary
      - run: |
          mkdir -p target/x86_64-unknown-linux-musl/release
          mv sia-interface target/x86_64-unknown-linux-musl/release/sia-interface
          chmod +x target/x86_64-unknown-linux-musl/release/sia-interface

      - name: Publish Image
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}  # it will be lowercased internally
          github_token: ${{ secrets.GITHUB_TOKEN }}

