name: Publish latest image
on:
  push:
    branches:
      - main

# When deployment at a time
concurrency:
  group: production
  cancel-in-progress: true

jobs:
  build_binary:
    uses: ./.github/workflows/build-binary.yml
    with:
      publish-artifact: true

  release_binary:
    needs: build_binary
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: built-binary
      - run: |
          chmod +x storj-interface
      - name: Generate release name
        run: echo "RELEASE_NAME=$(date +'%Y%m%d')-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Upload binary as latest release
        uses: softprops/action-gh-release@v2
        with:
          files: storj-interface
          make_latest: true
          fail_on_unmatched_files: true
          tag_name: ${{ env.RELEASE_NAME }}
      - name: Add key to ssh agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.HETZNER_SSH_PRIVATE_KEY }}
      - name: Add server as known host
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.HETZNER_BARE_METAL_DEPLOY_TARGET_SERVER_IPS }} >> ~/.ssh/known_hosts
      - name: Request update and restart
        run: |
          # Use the update script already on the server
          ssh root@${{ secrets.HETZNER_BARE_METAL_DEPLOY_TARGET_SERVER_IPS }} /usr/local/bin/update-storj-interface.sh
      - name: Run health check
        run: curl --fail https://storj-interface.yral.com/health

  publish_image:
    needs: build_binary
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: built-binary
      - run: |
          mkdir -p target/x86_64-unknown-linux-musl/release
          mv storj-interface target/x86_64-unknown-linux-musl/release/storj-interface
          chmod +x target/x86_64-unknown-linux-musl/release/storj-interface

      - name: Publish Image
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}  # it will be lowercased internally
          github_token: ${{ secrets.GITHUB_TOKEN }}

