name: Remove Specific SSH Key from Hetzner

on:
  workflow_dispatch:  # Manual trigger from GitHub UI

jobs:
  remove-key:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH Agent and Add Key
        run: |
            mkdir -p ~/.ssh
            eval "$(ssh-agent -s)"
            echo "${{ secrets.HETZNER_SSH_PRIVATE_KEY }}" | ssh-add -
            ssh-keyscan -H "storj-interface.yral.com" >> ~/.ssh/known_hosts
         

      - name: Remove tushar@gobazzinga.io key from authorized_keys
        run: |
            ssh root@storj-interface.yral.com << 'EOF'
            echo "Backing up authorized_keys..."
            cp ~/.ssh/authorized_keys ~/.ssh/authorized_keys.bak

            echo "Print the keys before"
            cat ~/.ssh/authorized_keys

            echo "Removing exact SSH key"
            sed -i '/ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIRZB6wnhwQPCwIQMgkG\/dlGTC1UTiiLRJSG7YzzN9B1 tushar@gobazzinga.io/d' ~/.ssh/authorized_keys

            echo "Done. Current keys:"
            cat ~/.ssh/authorized_keys
          EOF
